target 'NOMADVRSDK' do
  pod 'GVRSDK'
  pod 'GVRAudioSDK'
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'FileBrowser', '~> 1.0'
  use_frameworks!

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0' 
        end
    end
end
end
