#!/bin/bash

 # Copyright 2016-2018 Ruben Jesus Garcia Hernandez
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #     http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.

echo "Content-type: application/xhtml+xml"
echo ''
cat <<ENDA
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<title>Material configurator for VR viewing
</title>
</head>
<body>
<form action="/cgi-bin/NOMAD/configuredmaterial">
<fieldset>
	Material Number from NOMAD encyclopaedia <input type="text" name="material" 
ENDA


echo value=\"$QUERY_STRING\"


cat <<ENDB
/><br/>
	Background Color (RGB, 0-1)
		<input type="text" name="R" value="0"/>
		<input type="text" name="G" value="0"/>
		<input type="text" name="B" value="0"/><br/>
	Repetitions along a,b,c vectors of the unit cell
		<input type="text" name="Ra" value="1"/>
		<input type="text" name="Rb" value="1"/>
		<input type="text" name="Rc" value="1"/><br/>
	Show Trajectory of atoms (-1: all; otherwise empty or space separarated list of numbers)
		<input type="text" name="Traj" value=""/><br/>
	Screenshot Basename 
		<input type="text" name="Shot" value="C:\\temp\\frame"/><br/>
	<input type="submit" name="submit" value="Get Material"/>
</fieldset>
</form>
<p>
  <a href="http://validator.w3.org/check?uri=referer"><img
            src="/w3.org/valid-xhtml11.png"
            alt="Valid XHTML 1.1" height="31" width="88" /></a>
</p>
</body>
</html>
ENDB